version: "3.8"

volumes:
  SmartSchoolDb:

networks:
  dbNetwork:
  apiNetwork:

services:

  db:
    image: "mysql:5.7"
    container_name: mysql-smartschool
    ports:
      - "3306:3306"
    volumes:
      - SmartSchoolDb:/var/lib/mysql
    networks:
      - dbNetwork
    environment:
      - MYSQL_ROOT_PASSWORD=admin 
      - MYSQL_PASSWORD=admin 
      - MYSQL_ROOT_HOST=%
      - bind-address:0.0.0.0 

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-smartschool
    networks:
      - dbNetwork
      - apiNetwork
    ports:
      - 5000:80
    environment:
      - DBHOST=mysql
    depends_on:
      - db
